# Generated by Django 5.2.7 on 2025-10-12 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChesscomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Chess.com Username')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Country Code')),
                ('joined_date', models.DateTimeField(blank=True, null=True, verbose_name='Joined Date')),
                ('followers', models.IntegerField(default=0, verbose_name='Followers')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chess_profile', to=settings.AUTH_USER_MODEL, verbose_name='App User')),
            ],
            options={
                'verbose_name': 'Chess.com Player',
                'verbose_name_plural': 'Chess.com Players',
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_class', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid')], db_index=True, max_length=10, verbose_name='Time Class')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('rating_change', models.IntegerField(default=0, verbose_name='Rating Change')),
                ('total_games', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('draw_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.chesscomplayer')),
            ],
            options={
                'verbose_name': 'Player Rating',
                'verbose_name_plural': 'Player Ratings',
                'unique_together': {('player', 'time_class')},
            },
        ),
    ]
