# Generated by Django 5.2.7 on 2025-10-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chesscomplayer_playerrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesscomplayer',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='chesscomplayer',
            name='joined_date',
        ),
    ]
