# Generated by Django 5.2.7 on 2025-10-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField(verbose_name='PGN Data')),
                ('game_date', models.DateField(verbose_name='Game Date')),
                ('white_player', models.CharField(max_length=200, verbose_name='White Player')),
                ('black_player', models.CharField(max_length=200, verbose_name='Black Player')),
                ('time_control', models.CharField(max_length=50, verbose_name='Time Control')),
                ('result_description', models.CharField(max_length=50, verbose_name='Result')),
                ('moves_count', models.IntegerField(default=0, verbose_name='Move Count')),
                ('cached_at', models.DateTimeField(auto_now_add=True, verbose_name='Cached At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_games', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chess Game',
                'verbose_name_plural': 'Chess Games',
                'ordering': ['-game_date', '-cached_at'],
                'unique_together': {('user', 'pgn')},
            },
        ),
    ]
